/* eslint-env mocha */
'use strict'

// tests for example
// Generated by serverless-mocha-plugin

import mochaPlugin from 'serverless-mocha-plugin';
import dirtyChai from 'dirty-chai';
mochaPlugin.chai.use(dirtyChai);

const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('example', '/src/functions/example.js', 'example');

import AWS from 'aws-sdk-mock';
import AWS_SDK from 'aws-sdk';
AWS.setSDKInstance(AWS_SDK);


describe('example', () => {
  before((done) => {
    done();
  });

  it('implement tests here', () => {
    return wrapped.run({}).then((response) => {
      expect(response).to.not.be.empty();
    });
  });
});
